language: python

sudo: false



env:
  global:
  - PIP_DEPS="pytest coveralls pytest-cov flake8"



python:
- '3.6'



install:

- pip install -U tox-travis coverage coveralls

- travis_retry pip install $PIP_DEPS

- travis_retry pip install -r requirements.txt

- travis_retry pip install -e .



script:
- py.test --pyargs route_dynamics --cov-report term-missing --cov=route_dynamics
#- tox

- coverage report



after_success:
- coveralls



after_success:
- ls -a
- coveralls
