name: route_dynamics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy 
  - pandas
  - geopandas
  - folium
  - matplotlib
  - rasterio
  - branca
  - jupyter
  # - scikit-learn
  - pip
  - pip:
    - rasterstats
    - geopy


